
const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const zincColors = {
  50: "#fafafa",
  100: "#f4f4f5",
  200: "#e4e4e7",
  300: "#d4d4d8",
  400: "#a1a1aa",
  500: "#71717a",
  600: "#52525b",
  700: "#3f3f46",
  800: "#27272a",
  900: "#18181b",
  950: "#09090b",
};

export const appleBlue = "#007AFF";
export const appleRed = "#FF3B30";

export const borderColor = "#A1A1AA80";
export const appleGreen = "#34C759";
export const Colors = {
  light: {
    text: "#11181C",
    background: "#fff",
    tint: tintColorLight,
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#ECEDEE",
    background: "#151718",
    tint: tintColorDark,
    icon: "#9BA1A6",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
  },
};

export const backgroundColors = [
  "#fef2f2",
  "#fee2e2",
  "#fecaca",
  "#fca5a5",
  "#f87171",
  "#ef4444",
  "#dc2626",
  "#b91c1c",
  "#991b1b",
  "#7f1d1d",

  "#fff7ed",
  "#ffedd5",
  "#fed7aa",
  "#fdba74",
  "#fb923c",
  "#f97316",
  "#ea580c",
  "#c2410c",
  "#9a3412",
  "#7c2d12",

  "#fffbeb",
  "#fef3c7",
  "#fde68a",
  "#fcd34d",
  "#fbbf24",
  "#f59e0b",
  "#d97706",
  "#b45309",
  "#92400e",
  "#78350f",

  "#fefce8",
  "#fef9c3",
  "#fef08a",
  "#fde047",
  "#facc15",
  "#eab308",
  "#ca8a04",
  "#a16207",
  "#854d0e",
  "#713f12",

  "#f7fee7",
  "#ecfccb",
  "#d9f99d",
  "#bef264",
  "#a3e635",
  "#84cc16",
  "#65a30d",
  "#4d7c0f",
  "#3f6212",
  "#365314",

  "#f0fdf4",
  "#dcfce7",
  "#bbf7d0",
  "#86efac",
  "#4ade80",
  "#22c55e",
  "#16a34a",
  "#15803d",
  "#166534",
  "#14532d",

  "#ecfdf5",
  "#d1fae5",
  "#a7f3d0",
  "#6ee7b7",
  "#34d399",
  "#10b981",
  "#059669",
  "#047857",
  "#065f46",
  "#064e3b",

  "#f0fdfa",
  "#ccfbf1",
  "#99f6e4",
  "#5eead4",
  "#2dd4bf",
  "#14b8a6",
  "#0d9488",
  "#0f766e",
  "#115e59",
  "#134e4a",

  "#f0f9ff",
  "#e0f2fe",
  "#bae6fd",
  "#7dd3fc",
  "#38bdf8",
  "#0ea5e9",
  "#0284c7",
  "#0369a1",
  "#075985",
  "#0c4a6e",

  "#eff6ff",
  "#dbeafe",
  "#bfdbfe",
  "#93c5fd",
  "#60a5fa",
  "#3b82f6",
  "#2563eb",
  "#1d4ed8",
  "#1e40af",
  "#1e3a8a",

  "#eef2ff",
  "#e0e7ff",
  "#c7d2fe",
  "#a5b4fc",
  "#818cf8",
  "#6366f1",
  "#4f46e5",
  "#4338ca",
  "#3730a3",
  "#312e81",

  "#f5f3ff",
  "#ede9fe",
  "#ddd6fe",
  "#c4b5fd",
  "#a78bfa",
  "#8b5cf6",
  "#7c3aed",
  "#6d28d9",
  "#5b21b6",
  "#4c1d95",

  "#faf5ff",
  "#f3e8ff",
  "#e9d5ff",
  "#d8b4fe",
  "#c084fc",
  "#a855f7",
  "#9333ea",
  "#7e22ce",
  "#6b21a8",
  "#581c87",

  "#fdf4ff",
  "#fae8ff",
  "#f5d0fe",
  "#f0abfc",
  "#e879f9",
  "#d946ef",
  "#c026d3",
  "#a21caf",
  "#86198f",
  "#701a75",

  "#fdf2f8",
  "#fce7f3",
  "#fbcfe8",
  "#f9a8d4",
  "#f472b6",
  "#ec4899",
  "#db2777",
  "#be185d",
  "#9d174d",
  "#831843",

  "#fff1f2",
  "#ffe4e6",
  "#fecdd3",
  "#fda4af",
  "#fb7185",
  "#f43f5e",
  "#e11d48",
  "#be123c",
  "#9f1239",
  "#881337",
];

export const emojies = [
  // Fruits
  "🍏",
  "🍎",
  "🍐",
  "🍊",
  "🍋",
  "🍌",
  "🍉",
  "🍇",
  "🍓",
  "🫐",
  "🍈",
  "🍒",
  "🍑",
  "🥭",
  "🍍",
  "🥥",
  "🥝",

  // Vegetables
  "🍅",
  "🍆",
  "🥑",
  "🥦",
  "🥬",
  "🥒",
  "🌶",
  "🫑",
  "🌽",
  "🥕",
  "🥔",
  "🧄",
  "🧅",
  "🍄",

  // Breads & Bakery
  "🍞",
  "🥖",
  "🥨",
  "🥐",
  "🥯",

  // Dairy & Eggs
  "🧀",
  "🥚",
  "🍳",
  "🥞",
  "🧇",

  // Meats
  "🥓",
  "🥩",
  "🍗",
  "🍖",

  // Fast Foods
  "🌭",
  "🍔",
  "🍟",
  "🍕",

  // Wraps, Sandwiches & Ethnic Foods
  "🥪",
  "🌮",
  "🌯",
  "🫔",
  "🥙",
  "🧆",

  // Pasta, Rice & Asian Foods
  "🍜",
  "🍝",
  "🍣",
  "🍤",
  "🍙",
  "🍚",
  "🍛",
  "🍲",
  "🥘",
  "🥗",

  // Snacks & Misc
  "🍿",
  "🧈",
  "🥫",
  "🍱",
  "🥮",
  "🍠",
  "🍥",
  "🥟",
  "🥠",
  "🥡",

  // Desserts & Sweets
  "🍦",
  "🍧",
  "🍨",
  "🍩",
  "🍪",
  "🧁",
  "🍰",
  "🎂",
  "🍮",
  "🍭",
  "🍬",
  "🍫",
  "🍯",

  // Nuts
  "🥜",
  "🌰",

  // Drinks
  "🥛",
  "🧃",
  "🧉",
  "🥤",
  "🍶",
  "🍵",
  "🍺",
  "🍻",
  "🥂",
  "🍷",
  "🍸",
  "🍹",
  "🥃",
  "🍾",
  "☕️",
  "🫖",

  // Utensils & Condiments
  "🥄",
  "🍴",
  "🍽",
  "🥢",
  "🧂",

  // Shopping & Payment
  "🛒",
  "🛍️",
  "🧺",
  "💳",
  "💸",
  "💵",
  "💰",
  "💲",
  "🧾",
  "🔖",
  "🏪",
  "🏬",
  "🏦",
  "🏧",
  "📦",
  "📮",
  "🏷️",

  // Organizational / Utility
  "✅",
  "📋",
  "📜",
  "✏️",
  "📝",
  "🔍",
  "📆",
  "⏰",
  "📱",
  "💻",
  "🌐",
  "🔗",
  "🔒",
  "🔑",
  "🗃️",
  "🗂️",
  "🔄",
  "💡",
  "⭐️",
  "📌",
  "📍",
  "📊",
  "💯",
  "🎉",
  "🎊",
  "🎁",
  "🏆",
  "⚖️",
  "🏠",

  // Transportation & Movement (for shopping trips)
  "🚗",
  "🏃‍♂️",
  "🏃‍♀️",
  "🚶‍♂️",
  "🚶‍♀️",

  // Clothing (Items to buy)
  "👕",
  "👖",
  "👗",
  "👔",
  "🩳",
  "👠",
  "👟",
  "🧥",
  "🧤",
  "🧣",
  "🧦",
  "🎒",
  "👜",
  "👛",
  "👓",
  "🕶️",
  "👒",

  // Household Items (Things you might add to a shopping list)
  "🪣",
  "🪑",
  "🛋️",
  "🚪",
  "🪟",
  "🏺",
  "🖼️",
  "📺",
  "📻",
  "🔌",
  "🧴",
  "🪥",
  "🧹",
  "🧽",
  "🗑️",
  "🪒",
  "💊",
  "💉",
  "🩹",
  "❤️",
  "💔",
  "💘",
  "💙",
  "💚",
  "💛",
  "💜",
];

// Daily Whispers Theme Colors and Styles
export const DAILY_WHISPERS_THEMES = {
  youAreLoved: {
    id: 'youAreLoved',
    name: 'You Are Loved',
    emoji: '❤️',
    buttonColor: '#5d8aa8',
    pastelColor: '#c7dae1',
    description: '365 Days celebrating the importance of self-love and value - remind someone they are appreciated.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  funnySideOfLife: {
    id: 'funnySideOfLife',
    name: 'The Funny Side of Life',
    emoji: '😂',
    buttonColor: '#c32148',
    pastelColor: '#f4c2c2',
    description: 'Give someone a daily laugh with 365 days of funny quotes about being human.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  gratitudePearls: {
    id: 'gratitudePearls',
    name: 'Gratitude Pearls',
    emoji: '🦪',
    buttonColor: '#ed872d',
    pastelColor: '#fad6a5',
    description: 'Daily reminders to appreciate the simple joys and blessings in life, fostering a heart of gratitude.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  whispersFromNature: {
    id: 'whispersFromNature',
    name: 'Whispers from Nature',
    emoji: '🍃',
    buttonColor: '#a4c639',
    pastelColor: '#e8f1d4',
    description: '365 days of inspiration drawn from the natural world & our connection to it.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  aCatsLife: {
    id: 'aCatsLife',
    name: 'A Cat\'s Life',
    emoji: '🐱',
    buttonColor: '#0095b6',
    pastelColor: '#b3d9d9',
    description: '365 days of feline philosophy - celebrating independence & self-love.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  aDogsLife: {
    id: 'aDogsLife',
    name: 'A Dog\'s Life',
    emoji: '🐕',
    buttonColor: '#9f8c76',
    pastelColor: '#e3dac9',
    description: 'Daily lessons from our canine companions - celebrating loyalty & unconditional love.',
    price: 9.99,
    textColor: '#000000',
  },
  threadsOfConnection: {
    id: 'threadsOfConnection',
    name: 'Threads of Connection',
    emoji: '🤝',
    buttonColor: '#c35817',
    pastelColor: '#fbd5ab',
    description: '365 Days affirming Human Connection, the ways we touch each other\'s lives & our global community.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  motherhood: {
    id: 'motherhood',
    name: 'Motherhood',
    emoji: '🤱',
    buttonColor: '#d4a5a5',
    pastelColor: '#f5e6e6',
    description: '365 days celebrating the journey of motherhood - honoring strength, love, and the beautiful chaos of raising children.',
    price: 9.99,
    textColor: '#000000',
  },
};

export const DAILY_WHISPERS_BUNDLES = [
  {
    id: 'bestiesBundle',
    name: 'Besties Bundle',
    description: 'Get 3 quote sets',
    price: 18.99,
    count: 3,
    savings: '30% off',
  },
  {
    id: 'shareTheLoveBigTime',
    name: 'Share the Love Big Time',
    description: 'Get all 8 quote sets',
    price: 54.99,
    count: 8,
    savings: '30% off',
  },
];

// Sample quotes for each theme (3 examples shown, in real app would have 365)
export const DAILY_WHISPERS_QUOTES = {
  youAreLoved: [
    "You are worthy of love, exactly as you are.",
    "Your presence matters more than you know.",
    "Self-love is not selfish; it's essential.",
    "You deserve kindness, especially from yourself.",
    "Your value is not determined by others' opinions.",
    "You are enough, just as you are.",
    "Love yourself first, and everything else falls into line.",
    "You are a masterpiece in progress.",
    "Your heart is precious - treat it with care.",
    "You are loved beyond measure.",
  ],
  funnySideOfLife: [
    "Life is too short to take life too seriously.",
    "Laughter is the best medicine, and it's free.",
    "I'm not weird, I'm just limited edition.",
    "Adulting is like folding a fitted sheet - nobody really knows how to do it.",
    "Coffee: because adulting is hard.",
    "I'm not lazy, I'm on energy-saving mode.",
    "My bed is a magical place where I suddenly remember everything I forgot to do.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "Life is short. Smile while you still have teeth.",
    "I'm not clumsy, the floor just hates me.",
  ],
  gratitudePearls: [
    "Gratitude turns what we have into enough.",
    "Every moment is a gift; that's why it's called the present.",
    "Appreciate the little things; they are actually the big things.",
    "A grateful heart is a magnet for miracles.",
    "Thank you for the lessons, the growth, and the journey.",
    "Count your blessings, not your problems.",
    "Gratitude is the fairest blossom which springs from the soul.",
    "In all things, give thanks.",
    "The more grateful I am, the more beauty I see.",
    "Gratitude unlocks the fullness of life.",
  ],
  whispersFromNature: [
    "In nature, we find peace and perspective.",
    "The forest whispers secrets to those who listen.",
    "Nature doesn't hurry, yet everything is accomplished.",
    "Every flower is a tiny soul blossoming in nature.",
    "The earth has music for those who listen.",
    "Look deep into nature, and you will understand everything better.",
    "Nature is not a place to visit. It is home.",
    "The mountains are calling, and I must go.",
    "In every walk with nature, one receives far more than he seeks.",
    "The clearest way into the Universe is through a forest wilderness.",
  ],
  aCatsLife: [
    "Independence is not lonely; it's freedom.",
    "Cats know the secret: life is about balance and rest.",
    "Purr through life's challenges with grace.",
    "A cat's wisdom: do what makes you happy.",
    "Elegance is an attitude; cats know this well.",
    "Time spent with cats is never wasted.",
    "Cats choose us; we don't own them.",
    "In ancient times, cats were worshipped as gods. They have not forgotten this.",
    "A cat has absolute emotional honesty.",
    "Cats are connoisseurs of comfort.",
  ],
  aDogsLife: [
    "Love unconditionally, like a dog loves their human.",
    "Live in the moment; yesterday is gone, tomorrow hasn't come.",
    "Loyalty is a choice, and it's beautiful.",
    "A dog's joy is pure and infectious.",
    "Greet each day with enthusiasm, an open heart and a wagging tail.",
    "Dogs teach us about living in the present.",
    "The world would be a nicer place if everyone had the ability to love as unconditionally as a dog.",
    "Dogs are not our whole life, but they make our lives whole.",
    "Happiness is a warm puppy.",
    "Dogs do speak, but only to those who know how to listen.",
  ],
  threadsOfConnection: [
    "We are all connected by invisible threads of compassion.",
    "In helping others, we help ourselves.",
    "Community is where we find strength and belonging.",
    "Your kindness ripples through the world.",
    "Together, we are stronger than we ever could be alone.",
    "No act of kindness, no matter how small, is ever wasted.",
    "We rise by lifting others.",
    "Connection is why we're here; it gives purpose and meaning to our lives.",
    "Alone we can do so little; together we can do so much.",
    "The best way to find yourself is to lose yourself in the service of others.",
  ],
  motherhood: [
    "A mother's love is the fuel that enables a normal human being to do the impossible.",
    "Motherhood: All love begins and ends there.",
    "The days are long, but the years are short.",
    "Being a mother is learning about strengths you didn't know you had.",
    "A mother's arms are more comforting than anyone else's.",
    "Motherhood is the greatest thing and the hardest thing.",
    "You are doing better than you think you are.",
    "There is no way to be a perfect mother, but a million ways to be a good one.",
    "The heart of a mother is a deep abyss at the bottom of which you will always find forgiveness.",
    "A mother's love for her child is like nothing else in the world.",
    "Motherhood is a choice you make every day, to put someone else's happiness and well-being ahead of your own.",
    "Behind every young child who believes in themselves is a parent who believed first.",
    "To the world you are a mother, but to your family you are the world.",
    "A mother is she who can take the place of all others but whose place no one else can take.",
    "The influence of a mother in the lives of her children is beyond calculation.",
    "Mothers hold their children's hands for a short while, but their hearts forever.",
    "Being a mom has made me so tired. And so happy.",
    "A mother's love is patient and forgiving when all others are forsaking.",
    "Life doesn't come with a manual, it comes with a mother.",
    "Motherhood is the exquisite inconvenience of being another person's everything.",
    "The most important thing a father can do for his children is to love their mother.",
    "A mother's hug lasts long after she lets go.",
    "Motherhood: powered by love, fueled by coffee, sustained by wine.",
    "You will never look back on life and think, 'I spent too much time with my kids.'",
    "A mother's love is whole no matter how many times divided.",
    "Sometimes the strength of motherhood is greater than natural laws.",
    "Motherhood is a constant battle between going to bed to catch up on sleep or staying awake to finally get some alone time.",
    "The art of mothering is to teach the art of living to children.",
    "A mother's love doesn't make her son more dependent and timid; it actually makes him stronger and more independent.",
    "Being a mother is an attitude, not a biological relation.",
    "Motherhood is the biggest gamble in the world. It is the glorious life force.",
    "A mother's love is the heart of the family.",
    "Motherhood: where the days are long but the years are short.",
    "The natural state of motherhood is unselfishness.",
    "A mother's love is more beautiful than any fresh flower.",
    "Motherhood is learning about strengths you didn't know you had, and dealing with fears you didn't know existed.",
    "A mother's love is the strongest energy known to man.",
    "Motherhood is a journey that changes you forever.",
    "The moment a child is born, the mother is also born.",
    "A mother's love is unconditional, unselfish, and knows no boundaries.",
    "Motherhood is the greatest blessing and the hardest job.",
    "A mother's love is the purest form of love.",
    "Motherhood is not a hobby, it is a calling.",
    "A mother's love is the foundation of a child's life.",
    "Motherhood is the most challenging and rewarding job in the world.",
    "A mother's love is eternal and never-ending.",
    "Motherhood is a gift that keeps on giving.",
    "A mother's love is the light that guides us through the darkest times.",
    "Motherhood is a journey of self-discovery and growth.",
    "A mother's love is the anchor that holds the family together.",
    "Motherhood is a beautiful chaos.",
    "A mother's love is the greatest teacher.",
  ],
};

// APP CUSTOMIZATION - You can easily change these settings!
// HOW TO CUSTOMIZE:
// 1. To change backgrounds: Replace the URLs in backgroundImages below with any URL from BACKGROUND_OPTIONS
// 2. To add quote card graphics: Set showDecorations to true and add decorative text
// 3. All changes are made in this file - no need to edit other files!
export const APP_CUSTOMIZATION = {
  // Background image URLs for different screens
  // Change these to use different background images
  backgroundImages: {
    home: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=1600&fit=crop',
    purchaseOptions: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=1600&fit=crop',
  },
  
  // Quote card styling
  quoteCardStyle: {
    // Set to true to show decorative elements on quote cards
    showDecorations: false,
    // You can add custom decorative text/symbols here
    decorationTop: '',
    decorationBottom: '',
  },
};

// BACKGROUND IMAGE OPTIONS - Choose one for each screen
// Simply copy the URL you like and paste it into the backgroundImages object above
export const BACKGROUND_OPTIONS = {
  nature: [
    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=1600&fit=crop', // Flowers
    'https://images.unsplash.com/photo-1469022563149-aa64dbd37dae?w=1200&h=1600&fit=crop', // Forest
    'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200&h=1600&fit=crop', // Ocean
    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=1600&fit=crop', // Mountains
    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=1600&fit=crop', // Sunset
  ],
  abstract: [
    'https://images.unsplash.com/photo-1557672172-298e090d0f80?w=1200&h=1600&fit=crop', // Gradient
    'https://images.unsplash.com/photo-1557672172-298e090d0f80?w=1200&h=1600&fit=crop', // Watercolor
  ],
  minimal: [
    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=1600&fit=crop', // Light
  ],
};

// CUSTOMIZATION GUIDE - See CUSTOMIZATION_GUIDE.txt for detailed instructions
