
const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const zincColors = {
  50: "#fafafa",
  100: "#f4f4f5",
  200: "#e4e4e7",
  300: "#d4d4d8",
  400: "#a1a1aa",
  500: "#71717a",
  600: "#52525b",
  700: "#3f3f46",
  800: "#27272a",
  900: "#18181b",
  950: "#09090b",
};

export const appleBlue = "#007AFF";
export const appleRed = "#FF3B30";

export const borderColor = "#A1A1AA80";
export const appleGreen = "#34C759";
export const Colors = {
  light: {
    text: "#11181C",
    background: "#fff",
    tint: tintColorLight,
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#ECEDEE",
    background: "#151718",
    tint: tintColorDark,
    icon: "#9BA1A6",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
  },
};

export const backgroundColors = [
  "#fef2f2",
  "#fee2e2",
  "#fecaca",
  "#fca5a5",
  "#f87171",
  "#ef4444",
  "#dc2626",
  "#b91c1c",
  "#991b1b",
  "#7f1d1d",

  "#fff7ed",
  "#ffedd5",
  "#fed7aa",
  "#fdba74",
  "#fb923c",
  "#f97316",
  "#ea580c",
  "#c2410c",
  "#9a3412",
  "#7c2d12",

  "#fffbeb",
  "#fef3c7",
  "#fde68a",
  "#fcd34d",
  "#fbbf24",
  "#f59e0b",
  "#d97706",
  "#b45309",
  "#92400e",
  "#78350f",

  "#fefce8",
  "#fef9c3",
  "#fef08a",
  "#fde047",
  "#facc15",
  "#eab308",
  "#ca8a04",
  "#a16207",
  "#854d0e",
  "#713f12",

  "#f7fee7",
  "#ecfccb",
  "#d9f99d",
  "#bef264",
  "#a3e635",
  "#84cc16",
  "#65a30d",
  "#4d7c0f",
  "#3f6212",
  "#365314",

  "#f0fdf4",
  "#dcfce7",
  "#bbf7d0",
  "#86efac",
  "#4ade80",
  "#22c55e",
  "#16a34a",
  "#15803d",
  "#166534",
  "#14532d",

  "#ecfdf5",
  "#d1fae5",
  "#a7f3d0",
  "#6ee7b7",
  "#34d399",
  "#10b981",
  "#059669",
  "#047857",
  "#065f46",
  "#064e3b",

  "#f0fdfa",
  "#ccfbf1",
  "#99f6e4",
  "#5eead4",
  "#2dd4bf",
  "#14b8a6",
  "#0d9488",
  "#0f766e",
  "#115e59",
  "#134e4a",

  "#f0f9ff",
  "#e0f2fe",
  "#bae6fd",
  "#7dd3fc",
  "#38bdf8",
  "#0ea5e9",
  "#0284c7",
  "#0369a1",
  "#075985",
  "#0c4a6e",

  "#eff6ff",
  "#dbeafe",
  "#bfdbfe",
  "#93c5fd",
  "#60a5fa",
  "#3b82f6",
  "#2563eb",
  "#1d4ed8",
  "#1e40af",
  "#1e3a8a",

  "#eef2ff",
  "#e0e7ff",
  "#c7d2fe",
  "#a5b4fc",
  "#818cf8",
  "#6366f1",
  "#4f46e5",
  "#4338ca",
  "#3730a3",
  "#312e81",

  "#f5f3ff",
  "#ede9fe",
  "#ddd6fe",
  "#c4b5fd",
  "#a78bfa",
  "#8b5cf6",
  "#7c3aed",
  "#6d28d9",
  "#5b21b6",
  "#4c1d95",

  "#faf5ff",
  "#f3e8ff",
  "#e9d5ff",
  "#d8b4fe",
  "#c084fc",
  "#a855f7",
  "#9333ea",
  "#7e22ce",
  "#6b21a8",
  "#581c87",

  "#fdf4ff",
  "#fae8ff",
  "#f5d0fe",
  "#f0abfc",
  "#e879f9",
  "#d946ef",
  "#c026d3",
  "#a21caf",
  "#86198f",
  "#701a75",

  "#fdf2f8",
  "#fce7f3",
  "#fbcfe8",
  "#f9a8d4",
  "#f472b6",
  "#ec4899",
  "#db2777",
  "#be185d",
  "#9d174d",
  "#831843",

  "#fff1f2",
  "#ffe4e6",
  "#fecdd3",
  "#fda4af",
  "#fb7185",
  "#f43f5e",
  "#e11d48",
  "#be123c",
  "#9f1239",
  "#881337",
];

export const emojies = [
  // Fruits
  "🍏",
  "🍎",
  "🍐",
  "🍊",
  "🍋",
  "🍌",
  "🍉",
  "🍇",
  "🍓",
  "🫐",
  "🍈",
  "🍒",
  "🍑",
  "🥭",
  "🍍",
  "🥥",
  "🥝",

  // Vegetables
  "🍅",
  "🍆",
  "🥑",
  "🥦",
  "🥬",
  "🥒",
  "🌶",
  "🫑",
  "🌽",
  "🥕",
  "🥔",
  "🧄",
  "🧅",
  "🍄",

  // Breads & Bakery
  "🍞",
  "🥖",
  "🥨",
  "🥐",
  "🥯",

  // Dairy & Eggs
  "🧀",
  "🥚",
  "🍳",
  "🥞",
  "🧇",

  // Meats
  "🥓",
  "🥩",
  "🍗",
  "🍖",

  // Fast Foods
  "🌭",
  "🍔",
  "🍟",
  "🍕",

  // Wraps, Sandwiches & Ethnic Foods
  "🥪",
  "🌮",
  "🌯",
  "🫔",
  "🥙",
  "🧆",

  // Pasta, Rice & Asian Foods
  "🍜",
  "🍝",
  "🍣",
  "🍤",
  "🍙",
  "🍚",
  "🍛",
  "🍲",
  "🥘",
  "🥗",

  // Snacks & Misc
  "🍿",
  "🧈",
  "🥫",
  "🍱",
  "🥮",
  "🍠",
  "🍥",
  "🥟",
  "🥠",
  "🥡",

  // Desserts & Sweets
  "🍦",
  "🍧",
  "🍨",
  "🍩",
  "🍪",
  "🧁",
  "🍰",
  "🎂",
  "🍮",
  "🍭",
  "🍬",
  "🍫",
  "🍯",

  // Nuts
  "🥜",
  "🌰",

  // Drinks
  "🥛",
  "🧃",
  "🧉",
  "🥤",
  "🍶",
  "🍵",
  "🍺",
  "🍻",
  "🥂",
  "🍷",
  "🍸",
  "🍹",
  "🥃",
  "🍾",
  "☕️",
  "🫖",

  // Utensils & Condiments
  "🥄",
  "🍴",
  "🍽",
  "🥢",
  "🧂",

  // Shopping & Payment
  "🛒",
  "🛍️",
  "🧺",
  "💳",
  "💸",
  "💵",
  "💰",
  "💲",
  "🧾",
  "🔖",
  "🏪",
  "🏬",
  "🏦",
  "🏧",
  "📦",
  "📮",
  "🏷️",

  // Organizational / Utility
  "✅",
  "📋",
  "📜",
  "✏️",
  "📝",
  "🔍",
  "📆",
  "⏰",
  "📱",
  "💻",
  "🌐",
  "🔗",
  "🔒",
  "🔑",
  "🗃️",
  "🗂️",
  "🔄",
  "💡",
  "⭐️",
  "📌",
  "📍",
  "📊",
  "💯",
  "🎉",
  "🎊",
  "🎁",
  "🏆",
  "⚖️",
  "🏠",

  // Transportation & Movement (for shopping trips)
  "🚗",
  "🏃‍♂️",
  "🏃‍♀️",
  "🚶‍♂️",
  "🚶‍♀️",

  // Clothing (Items to buy)
  "👕",
  "👖",
  "👗",
  "👔",
  "🩳",
  "👠",
  "👟",
  "🧥",
  "🧤",
  "🧣",
  "🧦",
  "🎒",
  "👜",
  "👛",
  "👓",
  "🕶️",
  "👒",

  // Household Items (Things you might add to a shopping list)
  "🪣",
  "🪑",
  "🛋️",
  "🚪",
  "🪟",
  "🏺",
  "🖼️",
  "📺",
  "📻",
  "🔌",
  "🧴",
  "🪥",
  "🧹",
  "🧽",
  "🗑️",
  "🪒",
  "💊",
  "💉",
  "🩹",
  "❤️",
  "💔",
  "💘",
  "💙",
  "💚",
  "💛",
  "💜",
];

// Daily Whispers Theme Colors and Styles
export const DAILY_WHISPERS_THEMES = {
  youAreLoved: {
    id: 'youAreLoved',
    name: 'You Are Loved',
    emoji: '❤️',
    buttonColor: '#5d8aa8',
    pastelColor: '#c7dae1',
    description: '365 Days celebrating the importance of self-love and value - remind someone they are appreciated.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  funnySideOfLife: {
    id: 'funnySideOfLife',
    name: 'The Funny Side of Life',
    emoji: '😂',
    buttonColor: '#c32148',
    pastelColor: '#f4c2c2',
    description: 'Give someone a daily laugh with 365 days of funny quotes about being human.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  gratitudePearls: {
    id: 'gratitudePearls',
    name: 'Gratitude Pearls',
    emoji: '🦪',
    buttonColor: '#ed872d',
    pastelColor: '#fad6a5',
    description: 'Daily reminders to appreciate the simple joys and blessings in life, fostering a heart of gratitude.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  threadsOfConnection: {
    id: 'threadsOfConnection',
    name: 'Threads of Connection',
    emoji: '🤝',
    buttonColor: '#c35817',
    pastelColor: '#fbd5ab',
    description: '365 Days affirming Human Connection, the ways we touch each other\'s lives & our global community.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  motherhood: {
    id: 'motherhood',
    name: 'Motherhood',
    emoji: '🤱',
    buttonColor: '#d4a5a5',
    pastelColor: '#f5e6e6',
    description: 'Daily reminders to support the wonderful yet complex journey of motherhood.',
    price: 9.99,
    textColor: '#000000',
  },
  whispersFromNature: {
    id: 'whispersFromNature',
    name: 'Whispers from Nature',
    emoji: '🍃',
    buttonColor: '#a4c639',
    pastelColor: '#e8f1d4',
    description: '365 days of inspiration drawn from the natural world & our connection to it.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
  aDogsLife: {
    id: 'aDogsLife',
    name: 'A Dog\'s Life',
    emoji: '🐕',
    buttonColor: '#9f8c76',
    pastelColor: '#e3dac9',
    description: 'Daily lessons from our canine companions - celebrating loyalty & unconditional love.',
    price: 9.99,
    textColor: '#000000',
  },
  aCatsLife: {
    id: 'aCatsLife',
    name: 'A Cat\'s Life',
    emoji: '🐱',
    buttonColor: '#0095b6',
    pastelColor: '#b3d9d9',
    description: '365 days of feline philosophy - celebrating independence & self-love.',
    price: 9.99,
    textColor: '#FFFFFF',
  },
};

export const DAILY_WHISPERS_BUNDLES = [
  {
    id: 'bestiesBundle',
    name: 'Besties Bundle',
    description: 'Get 3 quote sets',
    price: 18.99,
    count: 3,
    savings: '30% off',
  },
  {
    id: 'shareTheLoveBigTime',
    name: 'Share the Love Big Time',
    description: 'Get all 8 quote sets',
    price: 54.99,
    count: 8,
    savings: '30% off',
  },
];

// Sample quotes for each theme (3 examples shown, in real app would have 365)
export const DAILY_WHISPERS_QUOTES = {
  youAreLoved: [
    "You are worthy of love, exactly as you are.",
    "Your presence matters more than you know.",
    "Self-love is not selfish; it's essential.",
    "You deserve kindness, especially from yourself.",
    "Your value is not determined by others' opinions.",
    "You are enough, just as you are.",
    "Love yourself first, and everything else falls into line.",
    "You are a masterpiece in progress.",
    "Your heart is precious - treat it with care.",
    "You are loved beyond measure.",
  ],
  funnySideOfLife: [
    "Life is too short to take life too seriously.",
    "Laughter is the best medicine, and it's free.",
    "I'm not weird, I'm just limited edition.",
    "Adulting is like folding a fitted sheet - nobody really knows how to do it.",
    "Coffee: because adulting is hard.",
    "I'm not lazy, I'm on energy-saving mode.",
    "My bed is a magical place where I suddenly remember everything I forgot to do.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "Life is short. Smile while you still have teeth.",
    "I'm not clumsy, the floor just hates me.",
  ],
  gratitudePearls: [
    "Gratitude turns what we have into enough.",
    "Every moment is a gift; that's why it's called the present.",
    "Appreciate the little things; they are actually the big things.",
    "A grateful heart is a magnet for miracles.",
    "Thank you for the lessons, the growth, and the journey.",
    "Count your blessings, not your problems.",
    "Gratitude is the fairest blossom which springs from the soul.",
    "In all things, give thanks.",
    "The more grateful I am, the more beauty I see.",
    "Gratitude unlocks the fullness of life.",
  ],
  threadsOfConnection: [
    "We are all connected by invisible threads of compassion.",
    "In helping others, we help ourselves.",
    "Community is where we find strength and belonging.",
    "Your kindness ripples through the world.",
    "Together, we are stronger than we ever could be alone.",
    "No act of kindness, no matter how small, is ever wasted.",
    "We rise by lifting others.",
    "Connection is why we're here; it gives purpose and meaning to our lives.",
    "Alone we can do so little; together we can do so much.",
    "The best way to find yourself is to lose yourself in the service of others.",
  ],
  motherhood: [
    "You are doing better than you think you are.",
    "There is no way to be a perfect mother, but a million ways to be a good one.",
    "Your best is always enough, even on the hardest days.",
    "Some days you will feel like you're failing. You're not. You're learning.",
    "The fact that you worry about being a good mom means you already are one.",
    "It's okay to not be okay. Tomorrow is a new day.",
    "You are stronger than you know, braver than you believe.",
    "The days are long, but the years are short. Cherish this moment.",
    "Your love is the greatest gift you can give your children.",
    "Being a mother means your heart lives outside your body.",
    "You don't have to be perfect. You just have to be present.",
    "Every mother doubts herself. You are not alone in this journey.",
    "The mess, the chaos, the exhaustion - it's all part of the beautiful journey.",
    "You are enough. You have always been enough.",
    "Motherhood is hard, but you are doing an amazing job.",
    "Take a deep breath. You've got this.",
    "Your children don't need a perfect mom. They need a happy one.",
    "It's okay to ask for help. Strength is knowing when you need support.",
    "The love between a mother and child is forever.",
    "You are raising tiny humans. That's the most important work there is.",
    "Some days, keeping everyone alive is a victory. Celebrate it.",
    "You are teaching your children how to be human. What a beautiful gift.",
    "The journey of motherhood is filled with both tears and laughter.",
    "Your patience, your love, your dedication - they matter more than you know.",
    "Behind every great kid is a mom who's pretty sure she's screwing it all up.",
    "Motherhood: where the days feel endless but the years fly by.",
    "You are creating memories that will last a lifetime.",
    "The world needs mothers like you - imperfect, real, and full of love.",
    "Your children are lucky to have you, exactly as you are.",
    "Every day you show up is a day you're winning at motherhood.",
    "The sleepless nights, the endless worries - they're all because you care so deeply.",
    "You are writing your family's story, one beautiful day at a time.",
    "Motherhood is the toughest job you'll ever love.",
    "Your love is shaping the future, one hug at a time.",
    "It's okay to feel overwhelmed. This is the hardest job in the world.",
    "You are doing sacred work, even when it doesn't feel like it.",
    "The little moments are actually the big moments.",
    "Your children will remember your love, not your mistakes.",
    "Being a mom means loving someone more than you ever thought possible.",
    "You are exactly the mother your children need.",
    "The journey is messy, chaotic, and absolutely beautiful.",
    "Your strength inspires your children every single day.",
    "Motherhood is a journey of becoming, not perfection.",
    "You are planting seeds of love that will bloom for generations.",
    "The tough days don't define you. Your love does.",
    "You are creating a home filled with love, and that's everything.",
    "Every mother's journey is unique and beautiful in its own way.",
    "You are enough, you have enough, you do enough.",
    "The world is a better place because you are someone's mother.",
    "Your love is the foundation your children will build their lives upon.",
  ],
  whispersFromNature: [
    "In nature, we find peace and perspective.",
    "The forest whispers secrets to those who listen.",
    "Nature doesn't hurry, yet everything is accomplished.",
    "Every flower is a tiny soul blossoming in nature.",
    "The earth has music for those who listen.",
    "Look deep into nature, and you will understand everything better.",
    "Nature is not a place to visit. It is home.",
    "The mountains are calling, and I must go.",
    "In every walk with nature, one receives far more than he seeks.",
    "The clearest way into the Universe is through a forest wilderness.",
  ],
  aDogsLife: [
    "Love unconditionally, like a dog loves their human.",
    "Live in the moment; yesterday is gone, tomorrow hasn't come.",
    "Loyalty is a choice, and it's beautiful.",
    "A dog's joy is pure and infectious.",
    "Greet each day with enthusiasm, an open heart and a wagging tail.",
    "Dogs teach us about living in the present.",
    "The world would be a nicer place if everyone had the ability to love as unconditionally as a dog.",
    "Dogs are not our whole life, but they make our lives whole.",
    "Happiness is a warm puppy.",
    "Dogs do speak, but only to those who know how to listen.",
  ],
  aCatsLife: [
    "Independence is not lonely; it's freedom.",
    "Cats know the secret: life is about balance and rest.",
    "Purr through life's challenges with grace.",
    "A cat's wisdom: do what makes you happy.",
    "Elegance is an attitude; cats know this well.",
    "Time spent with cats is never wasted.",
    "Cats choose us; we don't own them.",
    "In ancient times, cats were worshipped as gods. They have not forgotten this.",
    "A cat has absolute emotional honesty.",
    "Cats are connoisseurs of comfort.",
  ],
};

// APP CUSTOMIZATION - You can easily change these settings!
// HOW TO CUSTOMIZE:
// 1. To change backgrounds: Replace the URLs in backgroundImages below with any URL from BACKGROUND_OPTIONS
// 2. To add quote card graphics: Set showDecorations to true and add decorative text
// 3. All changes are made in this file - no need to edit other files!
export const APP_CUSTOMIZATION = {
  // Background image URLs for different screens
  // Change these to use different background images
  backgroundImages: {
    home: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=1600&fit=crop',
    purchaseOptions: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=1600&fit=crop',
  },
  
  // Quote card styling
  quoteCardStyle: {
    // Set to true to show decorative elements on quote cards
    showDecorations: false,
    // You can add custom decorative text/symbols here
    decorationTop: '',
    decorationBottom: '',
  },
};

// BACKGROUND IMAGE OPTIONS - Choose one for each screen
// Simply copy the URL you like and paste it into the backgroundImages object above
export const BACKGROUND_OPTIONS = {
  nature: [
    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=1600&fit=crop', // Flowers
    'https://images.unsplash.com/photo-1469022563149-aa64dbd37dae?w=1200&h=1600&fit=crop', // Forest
    'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200&h=1600&fit=crop', // Ocean
    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=1600&fit=crop', // Mountains
    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=1600&fit=crop', // Sunset
  ],
  abstract: [
    'https://images.unsplash.com/photo-1557672172-298e090d0f80?w=1200&h=1600&fit=crop', // Gradient
    'https://images.unsplash.com/photo-1557672172-298e090d0f80?w=1200&h=1600&fit=crop', // Watercolor
  ],
  minimal: [
    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=1600&fit=crop', // Light
  ],
};

// CUSTOMIZATION GUIDE - See CUSTOMIZATION_GUIDE.txt for detailed instructions
